"""empty message

Revision ID: 3128c9fcf69a
Revises: e437bdf4e912
Create Date: 2020-09-01 23:17:06.726437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3128c9fcf69a'
down_revision = 'e437bdf4e912'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('Show', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'created_date')
    op.drop_column('Show', 'created_date')
    op.drop_column('Artist', 'created_date')
    # ### end Alembic commands ###
